import java.util.Map;
import java.util.Set;
import java.util.TreeMap;

/**
 * Translates ACO-discovered covering inputs and target branches into a clean,
 * reproducible JUnit 4 test class (ACOTest.java) compatible with Defects4J
 * and the shared measurement pipeline (run_measurement.sh).
 */
public class JUnitGenerator {

    private static String javaStringLiteral(String value) {
        if (value == null) return "null";
        String escaped = value.replace("\\", "\\\\")
                .replace("\"", "\\\"")
                .replace("\t", "\\t")
                .replace("\n", "\\n")
                .replace("\r", "\\r");
        return "\"" + escaped + "\"";
    }

    public static String generate(Map<String, String> coveringInputs, String className, String packageName) {
        StringBuilder sb = new StringBuilder();
        sb.append("package ").append(packageName).append(";\n\n");
        sb.append("import static org.junit.Assert.*;\n");
        sb.append("import org.junit.Test;\n");
        sb.append("import java.math.BigDecimal;\n");
        sb.append("import java.math.BigInteger;\n\n");
        sb.append("/**\n");
        sb.append(" * Auto-generated by Ant Colony Optimization (ACO) test generator.\n");
        sb.append(" * Covers decision branches of org.apache.commons.lang3.math.NumberUtils.\n");
        sb.append(" */\n");
        sb.append("public class ").append(className).append(" {\n");

        Map<String, String> sorted = new TreeMap<>(coveringInputs);

        for (Map.Entry<String, String> entry : sorted.entrySet()) {
            String leafId = entry.getKey();
            String val = entry.getValue();
            String lit = javaStringLiteral(val);

            sb.append("\n    @Test\n");
            switch (leafId) {
                // =============================================================
                // 1. createNumber(String) Tests
                // =============================================================
                case "CN_NULL":
                    sb.append("    public void test_CN_null() {\n");
                    sb.append("        assertNull(NumberUtils.createNumber(null));\n");
                    sb.append("    }\n");
                    break;
                case "CN_BLANK_EMPTY":
                    sb.append("    public void test_CN_blankEmpty() {\n");
                    sb.append("        try {\n");
                    sb.append("            NumberUtils.createNumber(\"\");\n");
                    sb.append("            fail(\"Expected NumberFormatException\");\n");
                    sb.append("        } catch (NumberFormatException expected) {}\n");
                    sb.append("    }\n");
                    break;
                case "CN_BLANK_SPACE":
                    sb.append("    public void test_CN_blankSpace() {\n");
                    sb.append("        try {\n");
                    sb.append("            NumberUtils.createNumber(").append(lit).append(");\n");
                    sb.append("            fail(\"Expected NumberFormatException\");\n");
                    sb.append("        } catch (NumberFormatException expected) {}\n");
                    sb.append("    }\n");
                    break;
                case "CN_HEX_0x":
                    sb.append("    public void test_CN_hex_0x() {\n");
                    sb.append("        assertNotNull(NumberUtils.createNumber(").append(lit).append("));\n");
                    sb.append("    }\n");
                    break;
                case "CN_HEX_0X":
                    sb.append("    public void test_CN_hex_0X() {\n");
                    sb.append("        assertNotNull(NumberUtils.createNumber(").append(lit).append("));\n");
                    sb.append("    }\n");
                    break;
                case "CN_HEX_HASH":
                    sb.append("    public void test_CN_hex_hash() {\n");
                    sb.append("        assertNotNull(NumberUtils.createNumber(").append(lit).append("));\n");
                    sb.append("    }\n");
                    break;
                case "CN_HEX_NEG_0x":
                    sb.append("    public void test_CN_hex_neg_0x() {\n");
                    sb.append("        assertNotNull(NumberUtils.createNumber(").append(lit).append("));\n");
                    sb.append("    }\n");
                    break;
                case "CN_HEX_NEG_0X":
                    sb.append("    public void test_CN_hex_neg_0X() {\n");
                    sb.append("        assertNotNull(NumberUtils.createNumber(").append(lit).append("));\n");
                    sb.append("    }\n");
                    break;
                case "CN_HEX_NEG_HASH":
                    sb.append("    public void test_CN_hex_neg_hash() {\n");
                    sb.append("        assertNotNull(NumberUtils.createNumber(").append(lit).append("));\n");
                    sb.append("    }\n");
                    break;
                case "CN_HEX_LONG":
                    sb.append("    public void test_CN_hex_long() {\n");
                    sb.append("        Number res = NumberUtils.createNumber(").append(lit).append(");\n");
                    sb.append("        assertTrue(res instanceof Long || res instanceof BigInteger);\n");
                    sb.append("    }\n");
                    break;
                case "CN_HEX_BIGINT":
                    sb.append("    public void test_CN_hex_bigint() {\n");
                    sb.append("        Number res = NumberUtils.createNumber(").append(lit).append(");\n");
                    sb.append("        assertTrue(res instanceof BigInteger);\n");
                    sb.append("    }\n");
                    break;

                // --- LANG-747 Fault Detection Targets ---
                case "CN_LANG747_INT_FAULT":
                    sb.append("    public void test_CN_lang747_intBoundaryFault() {\n");
                    sb.append("        // Input: \"0x80000000\" - triggers LANG-747 fault on buggy version\n");
                    sb.append("        assertEquals(Long.valueOf(0x80000000L), NumberUtils.createNumber(\"0x80000000\"));\n");
                    sb.append("    }\n");
                    break;
                case "CN_LANG747_LONG_FAULT":
                    sb.append("    public void test_CN_lang747_longBoundaryFault() {\n");
                    sb.append("        // Input: \"0x8000000000000000\" - triggers LANG-747 fault on buggy version\n");
                    sb.append("        assertEquals(new BigInteger(\"8000000000000000\", 16), NumberUtils.createNumber(\"0x8000000000000000\"));\n");
                    sb.append("    }\n");
                    break;
                case "CN_LANG747_ZERO_INT":
                    sb.append("    public void test_CN_lang747_leadingZeroInt() {\n");
                    sb.append("        Number result = NumberUtils.createNumber(").append(lit).append(");\n");
                    sb.append("        assertTrue(\"Expected Integer but got \" + result.getClass().getSimpleName(), result instanceof Integer);\n");
                    sb.append("    }\n");
                    break;
                case "CN_LANG747_ZERO_LONG":
                    sb.append("    public void test_CN_lang747_leadingZeroLong() {\n");
                    sb.append("        Number result = NumberUtils.createNumber(").append(lit).append(");\n");
                    sb.append("        assertTrue(\"Expected Long but got \" + result.getClass().getSimpleName(), result instanceof Long);\n");
                    sb.append("    }\n");
                    break;

                // --- Exponent Paths ---
                case "CN_EXP_DEC":
                    sb.append("    public void test_CN_exp_decimal() {\n");
                    sb.append("        assertNotNull(NumberUtils.createNumber(").append(lit).append("));\n");
                    sb.append("    }\n");
                    break;
                case "CN_EXP_INT":
                    sb.append("    public void test_CN_exp_integer() {\n");
                    sb.append("        assertNotNull(NumberUtils.createNumber(").append(lit).append("));\n");
                    sb.append("    }\n");
                    break;
                case "CN_EXP_NEG":
                    sb.append("    public void test_CN_exp_negativePower() {\n");
                    sb.append("        assertNotNull(NumberUtils.createNumber(").append(lit).append("));\n");
                    sb.append("    }\n");
                    break;
                case "CN_EXP_ERR_DOUBLE":
                    sb.append("    public void test_CN_exp_errDoubleExp() {\n");
                    sb.append("        try {\n");
                    sb.append("            NumberUtils.createNumber(\"1.2e3e4\");\n");
                    sb.append("            fail(\"Expected NumberFormatException\");\n");
                    sb.append("        } catch (NumberFormatException expected) {}\n");
                    sb.append("    }\n");
                    break;
                case "CN_EXP_ERR_DOT":
                    sb.append("    public void test_CN_exp_errBeforeDot() {\n");
                    sb.append("        try {\n");
                    sb.append("            NumberUtils.createNumber(\"1e.5\");\n");
                    sb.append("            fail(\"Expected NumberFormatException\");\n");
                    sb.append("        } catch (NumberFormatException expected) {}\n");
                    sb.append("    }\n");
                    break;
                case "CN_EXP_ERR_END":
                    sb.append("    public void test_CN_exp_errAtEnd() {\n");
                    sb.append("        try {\n");
                    sb.append("            NumberUtils.createNumber(\"12e\");\n");
                    sb.append("            fail(\"Expected NumberFormatException\");\n");
                    sb.append("        } catch (NumberFormatException expected) {}\n");
                    sb.append("    }\n");
                    break;

                // --- Suffix L ---
                case "CN_SUF_L_POS":
                    sb.append("    public void test_CN_suffix_L_pos() {\n");
                    sb.append("        assertNotNull(NumberUtils.createNumber(").append(lit).append("));\n");
                    sb.append("    }\n");
                    break;
                case "CN_SUF_L_NEG":
                    sb.append("    public void test_CN_suffix_l_neg() {\n");
                    sb.append("        assertNotNull(NumberUtils.createNumber(").append(lit).append("));\n");
                    sb.append("    }\n");
                    break;
                case "CN_SUF_L_BIGINT":
                    sb.append("    public void test_CN_suffix_L_bigint() {\n");
                    sb.append("        Number res = NumberUtils.createNumber(\"999999999999999999999999999999L\");\n");
                    sb.append("        assertTrue(res instanceof BigInteger);\n");
                    sb.append("    }\n");
                    break;
                case "CN_SUF_L_ERR":
                    sb.append("    public void test_CN_suffix_L_err() {\n");
                    sb.append("        try {\n");
                    sb.append("            NumberUtils.createNumber(\"1.2L\");\n");
                    sb.append("            fail(\"Expected NumberFormatException\");\n");
                    sb.append("        } catch (NumberFormatException expected) {}\n");
                    sb.append("    }\n");
                    break;

                // --- Suffix F ---
                case "CN_SUF_F_POS":
                    sb.append("    public void test_CN_suffix_f_pos() {\n");
                    sb.append("        assertNotNull(NumberUtils.createNumber(").append(lit).append("));\n");
                    sb.append("    }\n");
                    break;
                case "CN_SUF_F_NEG":
                    sb.append("    public void test_CN_suffix_F_neg() {\n");
                    sb.append("        assertNotNull(NumberUtils.createNumber(").append(lit).append("));\n");
                    sb.append("    }\n");
                    break;
                case "CN_SUF_F_ZERO":
                    sb.append("    public void test_CN_suffix_f_zero() {\n");
                    sb.append("        assertEquals(Float.valueOf(0.0f), NumberUtils.createNumber(\"0.0f\"));\n");
                    sb.append("    }\n");
                    break;
                case "CN_SUF_F_OVERFLOW":
                    sb.append("    public void test_CN_suffix_f_overflow() {\n");
                    sb.append("        Number res = NumberUtils.createNumber(\"1e40f\");\n");
                    sb.append("        assertTrue(res instanceof Double);\n");
                    sb.append("    }\n");
                    break;
                case "CN_SUF_F_PRECISION":
                    sb.append("    public void test_CN_suffix_f_precision() {\n");
                    sb.append("        assertNotNull(NumberUtils.createNumber(\"1e-45f\"));\n");
                    sb.append("    }\n");
                    break;
                case "CN_SUF_F_ERR":
                    sb.append("    public void test_CN_suffix_f_err() {\n");
                    sb.append("        try {\n");
                    sb.append("            NumberUtils.createNumber(\"foo.f\");\n");
                    sb.append("            fail(\"Expected NumberFormatException\");\n");
                    sb.append("        } catch (NumberFormatException expected) {}\n");
                    sb.append("    }\n");
                    break;

                // --- Suffix D ---
                case "CN_SUF_D_POS":
                    sb.append("    public void test_CN_suffix_d_pos() {\n");
                    sb.append("        assertNotNull(NumberUtils.createNumber(").append(lit).append("));\n");
                    sb.append("    }\n");
                    break;
                case "CN_SUF_D_NEG":
                    sb.append("    public void test_CN_suffix_D_neg() {\n");
                    sb.append("        assertNotNull(NumberUtils.createNumber(").append(lit).append("));\n");
                    sb.append("    }\n");
                    break;
                case "CN_SUF_D_ZERO":
                    sb.append("    public void test_CN_suffix_d_zero() {\n");
                    sb.append("        assertEquals(Double.valueOf(0.0d), NumberUtils.createNumber(\"0.0d\"));\n");
                    sb.append("    }\n");
                    break;
                case "CN_SUF_D_OVERFLOW":
                    sb.append("    public void test_CN_suffix_d_overflow() {\n");
                    sb.append("        Number res = NumberUtils.createNumber(\"1e400d\");\n");
                    sb.append("        assertTrue(res instanceof BigDecimal);\n");
                    sb.append("    }\n");
                    break;
                case "CN_SUF_D_PRECISION":
                    sb.append("    public void test_CN_suffix_d_precision() {\n");
                    sb.append("        assertNotNull(NumberUtils.createNumber(\"1e-350d\"));\n");
                    sb.append("    }\n");
                    break;
                case "CN_SUF_D_ERR":
                    sb.append("    public void test_CN_suffix_d_err() {\n");
                    sb.append("        try {\n");
                    sb.append("            NumberUtils.createNumber(\"foo.d\");\n");
                    sb.append("            fail(\"Expected NumberFormatException\");\n");
                    sb.append("        } catch (NumberFormatException expected) {}\n");
                    sb.append("    }\n");
                    break;
                case "CN_SUF_ERR_CHAR":
                    sb.append("    public void test_CN_suffix_invalidChar() {\n");
                    sb.append("        try {\n");
                    sb.append("            NumberUtils.createNumber(\"123!\");\n");
                    sb.append("            fail(\"Expected NumberFormatException\");\n");
                    sb.append("        } catch (NumberFormatException expected) {}\n");
                    sb.append("    }\n");
                    break;

                // --- Plain Numbers ---
                case "CN_PLAIN_INT":
                    sb.append("    public void test_CN_plain_int() {\n");
                    sb.append("        assertNotNull(NumberUtils.createNumber(").append(lit).append("));\n");
                    sb.append("    }\n");
                    break;
                case "CN_PLAIN_ZERO":
                    sb.append("    public void test_CN_plain_zero() {\n");
                    sb.append("        assertEquals(Integer.valueOf(0), NumberUtils.createNumber(\"0\"));\n");
                    sb.append("    }\n");
                    break;
                case "CN_PLAIN_LONG_OVERFLOW":
                    sb.append("    public void test_CN_plain_longOverflow() {\n");
                    sb.append("        assertEquals(Long.valueOf(3000000000L), NumberUtils.createNumber(\"3000000000\"));\n");
                    sb.append("    }\n");
                    break;
                case "CN_PLAIN_BIGINT_OVERFLOW":
                    sb.append("    public void test_CN_plain_bigintOverflow() {\n");
                    sb.append("        assertEquals(new BigInteger(\"999999999999999999999999999999\"), NumberUtils.createNumber(\"999999999999999999999999999999\"));\n");
                    sb.append("    }\n");
                    break;

                // --- Decimals without Suffix ---
                case "CN_DEC_FLOAT":
                    sb.append("    public void test_CN_dec_float() {\n");
                    sb.append("        assertNotNull(NumberUtils.createNumber(").append(lit).append("));\n");
                    sb.append("    }\n");
                    break;
                case "CN_DEC_DOUBLE":
                    sb.append("    public void test_CN_dec_double() {\n");
                    sb.append("        assertNotNull(NumberUtils.createNumber(").append(lit).append("));\n");
                    sb.append("    }\n");
                    break;
                case "CN_DEC_BIGDEC":
                    sb.append("    public void test_CN_dec_bigDecimal() {\n");
                    sb.append("        assertNotNull(NumberUtils.createNumber(").append(lit).append("));\n");
                    sb.append("    }\n");
                    break;
                case "CN_DEC_FLOAT_OVERFLOW":
                    sb.append("    public void test_CN_dec_floatOverflow() {\n");
                    sb.append("        Number res = NumberUtils.createNumber(\"1e40\");\n");
                    sb.append("        assertTrue(res instanceof Double);\n");
                    sb.append("    }\n");
                    break;
                case "CN_DEC_DOUBLE_OVERFLOW":
                    sb.append("    public void test_CN_dec_doubleOverflow() {\n");
                    sb.append("        Number res = NumberUtils.createNumber(\"1e400\");\n");
                    sb.append("        assertTrue(res instanceof BigDecimal);\n");
                    sb.append("    }\n");
                    break;
                case "CN_DEC_ALL_ZEROS":
                    sb.append("    public void test_CN_dec_allZeros() {\n");
                    sb.append("        assertEquals(Float.valueOf(0.0f), NumberUtils.createNumber(\"0.0000\"));\n");
                    sb.append("    }\n");
                    break;

                // =============================================================
                // 2. isNumber(String) Tests
                // =============================================================
                case "IS_NULL_EMPTY":
                    sb.append("    public void test_IS_nullAndEmpty() {\n");
                    sb.append("        assertFalse(NumberUtils.isNumber(null));\n");
                    sb.append("        assertFalse(NumberUtils.isNumber(\"\"));\n");
                    sb.append("        assertFalse(NumberUtils.isNumber(\"   \"));\n");
                    sb.append("    }\n");
                    break;
                case "IS_HEX_VALID":
                    sb.append("    public void test_IS_hexValid() {\n");
                    sb.append("        assertTrue(NumberUtils.isNumber(\"0xABC123\"));\n");
                    sb.append("        assertTrue(NumberUtils.isNumber(\"-0xABC123\"));\n");
                    sb.append("        assertTrue(NumberUtils.isNumber(\"0x0\"));\n");
                    sb.append("    }\n");
                    break;
                case "IS_HEX_INVALID":
                    sb.append("    public void test_IS_hexInvalid() {\n");
                    sb.append("        assertFalse(NumberUtils.isNumber(\"0x\"));\n");
                    sb.append("        assertFalse(NumberUtils.isNumber(\"-0x\"));\n");
                    sb.append("        assertFalse(NumberUtils.isNumber(\"0xGF\"));\n");
                    sb.append("        assertFalse(NumberUtils.isNumber(\"0xFAE-1\"));\n");
                    sb.append("        assertFalse(NumberUtils.isNumber(\"-0ABC123\"));\n");
                    sb.append("    }\n");
                    break;
                case "IS_DEC_SIGNS":
                    sb.append("    public void test_IS_decSigns() {\n");
                    sb.append("        assertTrue(NumberUtils.isNumber(\"12345\"));\n");
                    sb.append("        assertTrue(NumberUtils.isNumber(\"-1234\"));\n");
                    sb.append("        assertTrue(NumberUtils.isNumber(\"1234.5\"));\n");
                    sb.append("        assertTrue(NumberUtils.isNumber(\".12345\"));\n");
                    sb.append("        assertTrue(NumberUtils.isNumber(\"0\"));\n");
                    sb.append("        assertTrue(NumberUtils.isNumber(\"-0\"));\n");
                    sb.append("    }\n");
                    break;
                case "IS_DEC_INVALID":
                    sb.append("    public void test_IS_decInvalid() {\n");
                    sb.append("        assertFalse(NumberUtils.isNumber(\".\"));\n");
                    sb.append("        assertFalse(NumberUtils.isNumber(\"--2.3\"));\n");
                    sb.append("        assertFalse(NumberUtils.isNumber(\".12.3\"));\n");
                    sb.append("        assertFalse(NumberUtils.isNumber(\"12..34\"));\n");
                    sb.append("    }\n");
                    break;
                case "IS_OCTAL":
                    sb.append("    public void test_IS_octal() {\n");
                    sb.append("        assertTrue(NumberUtils.isNumber(\"01234\"));\n");
                    sb.append("        assertTrue(NumberUtils.isNumber(\"-01234\"));\n");
                    sb.append("    }\n");
                    break;
                case "IS_EXP_VALID":
                    sb.append("    public void test_IS_expValid() {\n");
                    sb.append("        assertTrue(NumberUtils.isNumber(\"1234E5\"));\n");
                    sb.append("        assertTrue(NumberUtils.isNumber(\"1234E+5\"));\n");
                    sb.append("        assertTrue(NumberUtils.isNumber(\"1234E-5\"));\n");
                    sb.append("        assertTrue(NumberUtils.isNumber(\"123.4E5\"));\n");
                    sb.append("        assertTrue(NumberUtils.isNumber(\"-1234E5\"));\n");
                    sb.append("    }\n");
                    break;
                case "IS_EXP_INVALID":
                    sb.append("    public void test_IS_expInvalid() {\n");
                    sb.append("        assertFalse(NumberUtils.isNumber(\"-123E\"));\n");
                    sb.append("        assertFalse(NumberUtils.isNumber(\"-123E+-212\"));\n");
                    sb.append("        assertFalse(NumberUtils.isNumber(\"-123E2.12\"));\n");
                    sb.append("        assertFalse(NumberUtils.isNumber(\"123.4E-D\"));\n");
                    sb.append("        assertFalse(NumberUtils.isNumber(\"123.4ED\"));\n");
                    sb.append("        assertFalse(NumberUtils.isNumber(\"1234E5l\"));\n");
                    sb.append("    }\n");
                    break;
                case "IS_QUALIFIERS":
                    sb.append("    public void test_IS_qualifiers() {\n");
                    sb.append("        assertTrue(NumberUtils.isNumber(\"22338L\"));\n");
                    sb.append("        assertTrue(NumberUtils.isNumber(\"-221.23F\"));\n");
                    sb.append("        assertTrue(NumberUtils.isNumber(\"123.4E21D\"));\n");
                    sb.append("    }\n");
                    break;
                case "IS_INVALID_CHARS":
                    sb.append("    public void test_IS_invalidChars() {\n");
                    sb.append("        assertFalse(NumberUtils.isNumber(\"11a\"));\n");
                    sb.append("        assertFalse(NumberUtils.isNumber(\"1a\"));\n");
                    sb.append("        assertFalse(NumberUtils.isNumber(\"a\"));\n");
                    sb.append("        assertFalse(NumberUtils.isNumber(\"e\"));\n");
                    sb.append("    }\n");
                    break;

                // =============================================================
                // 3. Conversions Tests
                // =============================================================
                case "CV_TO_INT":
                    sb.append("    public void test_CV_toInt() {\n");
                    sb.append("        assertEquals(123, NumberUtils.toInt(\"123\"));\n");
                    sb.append("        assertEquals(0, NumberUtils.toInt(null));\n");
                    sb.append("        assertEquals(5, NumberUtils.toInt(null, 5));\n");
                    sb.append("        assertEquals(5, NumberUtils.toInt(\"invalid\", 5));\n");
                    sb.append("    }\n");
                    break;
                case "CV_TO_LONG":
                    sb.append("    public void test_CV_toLong() {\n");
                    sb.append("        assertEquals(123456789L, NumberUtils.toLong(\"123456789\"));\n");
                    sb.append("        assertEquals(0L, NumberUtils.toLong(null));\n");
                    sb.append("        assertEquals(5L, NumberUtils.toLong(null, 5L));\n");
                    sb.append("        assertEquals(5L, NumberUtils.toLong(\"invalid\", 5L));\n");
                    sb.append("    }\n");
                    break;
                case "CV_TO_FLOAT":
                    sb.append("    public void test_CV_toFloat() {\n");
                    sb.append("        assertEquals(1.5f, NumberUtils.toFloat(\"1.5\"), 0.001f);\n");
                    sb.append("        assertEquals(0.0f, NumberUtils.toFloat(null), 0.001f);\n");
                    sb.append("        assertEquals(5.5f, NumberUtils.toFloat(null, 5.5f), 0.001f);\n");
                    sb.append("        assertEquals(5.5f, NumberUtils.toFloat(\"invalid\", 5.5f), 0.001f);\n");
                    sb.append("    }\n");
                    break;
                case "CV_TO_DOUBLE":
                    sb.append("    public void test_CV_toDouble() {\n");
                    sb.append("        assertEquals(1.5d, NumberUtils.toDouble(\"1.5\"), 0.001d);\n");
                    sb.append("        assertEquals(0.0d, NumberUtils.toDouble(null), 0.001d);\n");
                    sb.append("        assertEquals(5.5d, NumberUtils.toDouble(null, 5.5d), 0.001d);\n");
                    sb.append("        assertEquals(5.5d, NumberUtils.toDouble(\"invalid\", 5.5d), 0.001d);\n");
                    sb.append("    }\n");
                    break;
                case "CV_TO_BYTE":
                    sb.append("    public void test_CV_toByte() {\n");
                    sb.append("        assertEquals((byte)12, NumberUtils.toByte(\"12\"));\n");
                    sb.append("        assertEquals((byte)0, NumberUtils.toByte(null));\n");
                    sb.append("        assertEquals((byte)5, NumberUtils.toByte(null, (byte)5));\n");
                    sb.append("        assertEquals((byte)5, NumberUtils.toByte(\"invalid\", (byte)5));\n");
                    sb.append("    }\n");
                    break;
                case "CV_TO_SHORT":
                    sb.append("    public void test_CV_toShort() {\n");
                    sb.append("        assertEquals((short)123, NumberUtils.toShort(\"123\"));\n");
                    sb.append("        assertEquals((short)0, NumberUtils.toShort(null));\n");
                    sb.append("        assertEquals((short)5, NumberUtils.toShort(null, (short)5));\n");
                    sb.append("        assertEquals((short)5, NumberUtils.toShort(\"invalid\", (short)5));\n");
                    sb.append("    }\n");
                    break;

                // =============================================================
                // 4. Min / Max Tests
                // =============================================================
                case "MM_LONG_ARR":
                    sb.append("    public void test_MM_longArray() {\n");
                    sb.append("        assertEquals(1L, NumberUtils.min(new long[]{3L, 1L, 2L}));\n");
                    sb.append("        assertEquals(3L, NumberUtils.max(new long[]{1L, 3L, 2L}));\n");
                    sb.append("        try { NumberUtils.min((long[])null); fail(); } catch (IllegalArgumentException e) {}\n");
                    sb.append("        try { NumberUtils.min(new long[0]); fail(); } catch (IllegalArgumentException e) {}\n");
                    sb.append("        try { NumberUtils.max((long[])null); fail(); } catch (IllegalArgumentException e) {}\n");
                    sb.append("        try { NumberUtils.max(new long[0]); fail(); } catch (IllegalArgumentException e) {}\n");
                    sb.append("    }\n");
                    break;
                case "MM_INT_ARR":
                    sb.append("    public void test_MM_intArray() {\n");
                    sb.append("        assertEquals(1, NumberUtils.min(new int[]{3, 1, 2}));\n");
                    sb.append("        assertEquals(3, NumberUtils.max(new int[]{1, 3, 2}));\n");
                    sb.append("        try { NumberUtils.min((int[])null); fail(); } catch (IllegalArgumentException e) {}\n");
                    sb.append("        try { NumberUtils.min(new int[0]); fail(); } catch (IllegalArgumentException e) {}\n");
                    sb.append("        try { NumberUtils.max((int[])null); fail(); } catch (IllegalArgumentException e) {}\n");
                    sb.append("        try { NumberUtils.max(new int[0]); fail(); } catch (IllegalArgumentException e) {}\n");
                    sb.append("    }\n");
                    break;
                case "MM_SHORT_ARR":
                    sb.append("    public void test_MM_shortArray() {\n");
                    sb.append("        assertEquals((short)1, NumberUtils.min(new short[]{3, 1, 2}));\n");
                    sb.append("        assertEquals((short)3, NumberUtils.max(new short[]{1, 3, 2}));\n");
                    sb.append("        try { NumberUtils.min((short[])null); fail(); } catch (IllegalArgumentException e) {}\n");
                    sb.append("        try { NumberUtils.min(new short[0]); fail(); } catch (IllegalArgumentException e) {}\n");
                    sb.append("        try { NumberUtils.max((short[])null); fail(); } catch (IllegalArgumentException e) {}\n");
                    sb.append("        try { NumberUtils.max(new short[0]); fail(); } catch (IllegalArgumentException e) {}\n");
                    sb.append("    }\n");
                    break;
                case "MM_BYTE_ARR":
                    sb.append("    public void test_MM_byteArray() {\n");
                    sb.append("        assertEquals((byte)1, NumberUtils.min(new byte[]{3, 1, 2}));\n");
                    sb.append("        assertEquals((byte)3, NumberUtils.max(new byte[]{1, 3, 2}));\n");
                    sb.append("        try { NumberUtils.min((byte[])null); fail(); } catch (IllegalArgumentException e) {}\n");
                    sb.append("        try { NumberUtils.min(new byte[0]); fail(); } catch (IllegalArgumentException e) {}\n");
                    sb.append("        try { NumberUtils.max((byte[])null); fail(); } catch (IllegalArgumentException e) {}\n");
                    sb.append("        try { NumberUtils.max(new byte[0]); fail(); } catch (IllegalArgumentException e) {}\n");
                    sb.append("    }\n");
                    break;
                case "MM_DOUBLE_ARR":
                    sb.append("    public void test_MM_doubleArray() {\n");
                    sb.append("        assertEquals(1.0, NumberUtils.min(new double[]{3.0, 1.0, 2.0}), 0.001);\n");
                    sb.append("        assertEquals(3.0, NumberUtils.max(new double[]{1.0, 3.0, 2.0}), 0.001);\n");
                    sb.append("        assertTrue(Double.isNaN(NumberUtils.min(new double[]{1.0, Double.NaN})));\n");
                    sb.append("        assertTrue(Double.isNaN(NumberUtils.max(new double[]{1.0, Double.NaN})));\n");
                    sb.append("        try { NumberUtils.min((double[])null); fail(); } catch (IllegalArgumentException e) {}\n");
                    sb.append("        try { NumberUtils.min(new double[0]); fail(); } catch (IllegalArgumentException e) {}\n");
                    sb.append("        try { NumberUtils.max((double[])null); fail(); } catch (IllegalArgumentException e) {}\n");
                    sb.append("        try { NumberUtils.max(new double[0]); fail(); } catch (IllegalArgumentException e) {}\n");
                    sb.append("    }\n");
                    break;
                case "MM_FLOAT_ARR":
                    sb.append("    public void test_MM_floatArray() {\n");
                    sb.append("        assertEquals(1.0f, NumberUtils.min(new float[]{3.0f, 1.0f, 2.0f}), 0.001f);\n");
                    sb.append("        assertEquals(3.0f, NumberUtils.max(new float[]{1.0f, 3.0f, 2.0f}), 0.001f);\n");
                    sb.append("        assertTrue(Float.isNaN(NumberUtils.min(new float[]{1.0f, Float.NaN})));\n");
                    sb.append("        assertTrue(Float.isNaN(NumberUtils.max(new float[]{1.0f, Float.NaN})));\n");
                    sb.append("        try { NumberUtils.min((float[])null); fail(); } catch (IllegalArgumentException e) {}\n");
                    sb.append("        try { NumberUtils.min(new float[0]); fail(); } catch (IllegalArgumentException e) {}\n");
                    sb.append("        try { NumberUtils.max((float[])null); fail(); } catch (IllegalArgumentException e) {}\n");
                    sb.append("        try { NumberUtils.max(new float[0]); fail(); } catch (IllegalArgumentException e) {}\n");
                    sb.append("    }\n");
                    break;
                case "MM_3ARG_INT":
                    sb.append("    public void test_MM_3argInt() {\n");
                    sb.append("        assertEquals(1, NumberUtils.min(3, 1, 2));\n");
                    sb.append("        assertEquals(1, NumberUtils.min(2, 3, 1));\n");
                    sb.append("        assertEquals(3, NumberUtils.max(1, 3, 2));\n");
                    sb.append("        assertEquals(3, NumberUtils.max(2, 1, 3));\n");
                    sb.append("    }\n");
                    break;
                case "MM_3ARG_LONG":
                    sb.append("    public void test_MM_3argLong() {\n");
                    sb.append("        assertEquals(1L, NumberUtils.min(3L, 1L, 2L));\n");
                    sb.append("        assertEquals(1L, NumberUtils.min(2L, 3L, 1L));\n");
                    sb.append("        assertEquals(3L, NumberUtils.max(1L, 3L, 2L));\n");
                    sb.append("        assertEquals(3L, NumberUtils.max(2L, 1L, 3L));\n");
                    sb.append("    }\n");
                    break;
                case "MM_3ARG_SHORT":
                    sb.append("    public void test_MM_3argShort() {\n");
                    sb.append("        assertEquals((short)1, NumberUtils.min((short)3, (short)1, (short)2));\n");
                    sb.append("        assertEquals((short)1, NumberUtils.min((short)2, (short)3, (short)1));\n");
                    sb.append("        assertEquals((short)3, NumberUtils.max((short)1, (short)3, (short)2));\n");
                    sb.append("        assertEquals((short)3, NumberUtils.max((short)2, (short)1, (short)3));\n");
                    sb.append("    }\n");
                    break;
                case "MM_3ARG_BYTE":
                    sb.append("    public void test_MM_3argByte() {\n");
                    sb.append("        assertEquals((byte)1, NumberUtils.min((byte)3, (byte)1, (byte)2));\n");
                    sb.append("        assertEquals((byte)1, NumberUtils.min((byte)2, (byte)3, (byte)1));\n");
                    sb.append("        assertEquals((byte)3, NumberUtils.max((byte)1, (byte)3, (byte)2));\n");
                    sb.append("        assertEquals((byte)3, NumberUtils.max((byte)2, (byte)1, (byte)3));\n");
                    sb.append("    }\n");
                    break;
                case "MM_3ARG_DOUBLE":
                    sb.append("    public void test_MM_3argDouble() {\n");
                    sb.append("        assertEquals(1.0, NumberUtils.min(3.0, 1.0, 2.0), 0.001);\n");
                    sb.append("        assertEquals(1.0, NumberUtils.min(2.0, 3.0, 1.0), 0.001);\n");
                    sb.append("        assertEquals(3.0, NumberUtils.max(1.0, 3.0, 2.0), 0.001);\n");
                    sb.append("        assertEquals(3.0, NumberUtils.max(2.0, 1.0, 3.0), 0.001);\n");
                    sb.append("        assertTrue(Double.isNaN(NumberUtils.min(Double.NaN, 1.0, 2.0)));\n");
                    sb.append("        assertTrue(Double.isNaN(NumberUtils.max(1.0, Double.NaN, 2.0)));\n");
                    sb.append("    }\n");
                    break;
                case "MM_3ARG_FLOAT":
                    sb.append("    public void test_MM_3argFloat() {\n");
                    sb.append("        assertEquals(1.0f, NumberUtils.min(3.0f, 1.0f, 2.0f), 0.001f);\n");
                    sb.append("        assertEquals(1.0f, NumberUtils.min(2.0f, 3.0f, 1.0f), 0.001f);\n");
                    sb.append("        assertEquals(3.0f, NumberUtils.max(1.0f, 3.0f, 2.0f), 0.001f);\n");
                    sb.append("        assertEquals(3.0f, NumberUtils.max(2.0f, 1.0f, 3.0f), 0.001f);\n");
                    sb.append("        assertTrue(Float.isNaN(NumberUtils.min(Float.NaN, 1.0f, 2.0f)));\n");
                    sb.append("        assertTrue(Float.isNaN(NumberUtils.max(1.0f, Float.NaN, 2.0f)));\n");
                    sb.append("    }\n");
                    break;

                // =============================================================
                // 5. Direct Creators Tests
                // =============================================================
                case "CR_INT_LONG":
                    sb.append("    public void test_CR_intAndLong() {\n");
                    sb.append("        assertNull(NumberUtils.createInteger(null));\n");
                    sb.append("        assertEquals(Integer.valueOf(123), NumberUtils.createInteger(\"123\"));\n");
                    sb.append("        assertNull(NumberUtils.createLong(null));\n");
                    sb.append("        assertEquals(Long.valueOf(123L), NumberUtils.createLong(\"123\"));\n");
                    sb.append("    }\n");
                    break;
                case "CR_FLOAT_DOUBLE":
                    sb.append("    public void test_CR_floatAndDouble() {\n");
                    sb.append("        assertNull(NumberUtils.createFloat(null));\n");
                    sb.append("        assertEquals(Float.valueOf(1.5f), NumberUtils.createFloat(\"1.5\"));\n");
                    sb.append("        assertNull(NumberUtils.createDouble(null));\n");
                    sb.append("        assertEquals(Double.valueOf(1.5d), NumberUtils.createDouble(\"1.5\"));\n");
                    sb.append("    }\n");
                    break;
                case "CR_BIGDEC":
                    sb.append("    public void test_CR_bigDecimal() {\n");
                    sb.append("        assertNull(NumberUtils.createBigDecimal(null));\n");
                    sb.append("        assertEquals(new BigDecimal(\"123.45\"), NumberUtils.createBigDecimal(\"123.45\"));\n");
                    sb.append("        try { NumberUtils.createBigDecimal(\"\"); fail(); } catch (NumberFormatException e) {}\n");
                    sb.append("        try { NumberUtils.createBigDecimal(\"   \"); fail(); } catch (NumberFormatException e) {}\n");
                    sb.append("    }\n");
                    break;
                case "CR_BIGINT":
                    sb.append("    public void test_CR_bigInteger() {\n");
                    sb.append("        assertNull(NumberUtils.createBigInteger(null));\n");
                    sb.append("        assertEquals(new BigInteger(\"1234\"), NumberUtils.createBigInteger(\"1234\"));\n");
                    sb.append("        assertEquals(new BigInteger(\"-1234\"), NumberUtils.createBigInteger(\"-1234\"));\n");
                    sb.append("        assertEquals(new BigInteger(\"1234\", 16), NumberUtils.createBigInteger(\"0x1234\"));\n");
                    sb.append("        assertEquals(new BigInteger(\"1234\", 16), NumberUtils.createBigInteger(\"#1234\"));\n");
                    sb.append("        assertEquals(new BigInteger(\"1234\", 8), NumberUtils.createBigInteger(\"01234\"));\n");
                    sb.append("        assertEquals(new BigInteger(\"-1234\", 16), NumberUtils.createBigInteger(\"-0x1234\"));\n");
                    sb.append("        assertEquals(new BigInteger(\"-1234\", 8), NumberUtils.createBigInteger(\"-01234\"));\n");
                    sb.append("    }\n");
                    break;
                case "CR_IS_DIGITS":
                    sb.append("    public void test_CR_isDigits() {\n");
                    sb.append("        assertFalse(NumberUtils.isDigits(null));\n");
                    sb.append("        assertFalse(NumberUtils.isDigits(\"\"));\n");
                    sb.append("        assertTrue(NumberUtils.isDigits(\"12345\"));\n");
                    sb.append("        assertFalse(NumberUtils.isDigits(\"12a34\"));\n");
                    sb.append("    }\n");
                    break;
                case "CR_CONSTRUCTOR":
                    sb.append("    public void test_CR_constructor() {\n");
                    sb.append("        assertNotNull(new NumberUtils());\n");
                    sb.append("    }\n");
                    break;

                default:
                    sb.append("    public void test_").append(leafId).append("() {\n");
                    sb.append("        assertNotNull(NumberUtils.createNumber(").append(lit).append("));\n");
                    sb.append("    }\n");
                    break;
            }
        }

        sb.append("}\n");
        return sb.toString();
    }
}
